const types = {
  OPEN_LOGIN_MODAL: 'OPEN_LOGIN_MODAL',
  OPEN_SIGNUP_MODAL: 'OPEN_SIGNUP_MODAL',
  OPEN_RESET_PASS_MODAL: 'OPEN_RESET_PASS_MODAL',
  CLOSE_AUTH_MODALS: 'CLOSE_AUTH_MODALS'
};

export default types;
